version: "3.9"

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jekins:
    image: jenkins/jenkins
    ports:
      - 8088:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
